---
title: "ds-4100-project.Rmd"
author: "Veronica Shei, Edward Wang, Ethan Tang"
date: "3/23/2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rvest)
library(tidyverse)
library(RSQLite)
library(fTrading)
library(ggplot2)
library(quantmod)
db <- dbConnect(SQLite(), dbname = "ds4100_project_db.sqlite")
```

#retrieve S&P 500 company tickers
```{r, sp500, message=FALSE, echo=TRUE, warning=FALSE}
#Using web scraping to retrieve a list of the names of companies in the s&p 500
sp500_page <- read_html("https://en.wikipedia.org/wiki/List_of_S%26P_500_companies")
sp500_tickers <- sp500_page %>% html_nodes("#constituents td:nth-child(2)") %>% html_text()
sp500_tickers <- replace(sp500_tickers, sp500_tickers == "BRK.B", "BRK-B")
sp500_tickers <- replace(sp500_tickers, sp500_tickers == "BF.B", "BF-B")
```

```{r, SMA, message=FALSE, echo=TRUE, warning=FALSE}
#Return the simple moving average.
#The SMA is calculated as the arithmetic average of an asset's price over some period.
#The SMA is a technical indicator for determining if an asset price will continue or reverse a bull or bear trend.
get_SMA <- function(ticker_df) {
  sma <- SMA(ticker_df[,6])
  sma <- replace_na(sma, 0)
  sma
}
```

```{r, EWMA, message=FALSE, echo=TRUE, warning=FALSE}
#Return the Exponentially Weighted Moving Average.
#SMA weights each return evenly, but data but returns from a year ago do not represent what returns would be the last week.
#EWMA introduces lambda, which is called the smoothing parameter, fixing the problem by giving recent returns greater weight on the variance.
get_EWMA <- function(ticker_df) {
  EWMA(ticker_df[,6], lambda = .1)
}
```

```{r, MOM, message=FALSE, echo=TRUE, warning=FALSE}
#Return the Momentum Indicator.
#Momentum mesaures the speed/velocity of price changes (rate of the rise and fall of stock prices).
#From the standpoint of trending, momentum is a very useful indicator of strength or weakness in the issue's price.
#It has been found to be more useful during times of a rising market rather than falling.
MOM <- function(ticker_df) {
  momTA(ticker_df[,6]) #momentum 
}
```

```{r, MACD, message=FALSE, echo=TRUE, warning=FALSE}
#Return the Moving Average Convergence Divergence
# Trend-following momentum indicator that shows the relationship between two moving averages of a security's price.
MACD <- function(ticker_df) {
  macdTA(ticker_df[,6]) 
}
```

```{r, STOCH, message=FALSE, echo=TRUE, warning=FALSE}
# Returns the Stochastics Oscillator indiciator
# It is a momentum indicator comparing a particular closing price of a security to a range of its prices over a certain period of time.
# A stochastic oscillator is a popular technical indicator for generating overbought and oversold signals.
STOCH <- function(ticker_df) {
  stochasticTA(ticker_df[,4], ticker_df[,2], ticker_df[,3])
}
```

```{r, RSI, message=FALSE, echo=TRUE, warning=FALSE}
# Return the relative strength index
# indicates to the trader whether or not an issue's price action is created by those over-buying or over-selling it. 
RSI <- function(ticker_df){
  rsiTA(ticker_df[,6]) 
}
```

```{r, VOR, message=FALSE, echo=TRUE, warning=FALSE}
# Return the volatility ratio.
# measure that helps investors follow the volatility of a stock's price. 
# used to identify price patterns and breakouts.
VOR <- function(ticker_df) {
  vorTA(ticker_df[,2], ticker_df[,3])
}
```

```{r, percent_values, message=FALSE, echo=TRUE, warning=FALSE}
# Function to calculate the percent values for price and volume.
get_percent_values <- function(ticker_df, type) {
  if (type == "price") {
    curr_val <- (dplyr::lead(ticker_df[,6], 1) - ticker_df[,6]) / ticker_df[,6] * 100
  } else if (type == "volume") {
    curr_val <- (dplyr::lead(ticker_df[,5], 1) - ticker_df[,5]) / ticker_df[,5] * 100
  }
  curr_val <- c(0, curr_val[1:length(curr_val) - 1])
  curr_val
}
```

```{r, future_percent_change, message=FALSE, echo=TRUE, warning=FALSE}
# Function to calculate the future percent change of a stock.
# num_days is how the difference is calculated: use 20, 60, 240.
get_future_percent_change <- function(ticker_df, num_days) {
  curr_val <- (dplyr::lead(ticker_df[,6], num_days) - ticker_df[,6]) /
      ticker_df[,6] * 100
  curr_val
}
```

```{r, buy_class, message=FALSE, echo=TRUE, warning=FALSE}
# Function to calculate whether or not to buy a stock. 
# num_days is how the difference is calculated: use 20, 60, 240
get_buy_class <- function(ticker_df, num_days) {
  buy_class <- dplyr::lead(ticker_df[,6], num_days) > ticker_df[,6]
  as.numeric(buy_class)
}
```


```{r, stock_data, message=FALSE, echo=TRUE, warning=FALSE}
# Function to pull the stock data for 5 years for the S&P 500 companies from quant mod.
for(ticker in sp500_tickers) {
  getSymbols(ticker, from='2014-04-16', to='2019-04-16')
  assign(ticker, data.frame(get(ticker)))
  assign(ticker, na.omit(get(ticker)))
}
```

```{r, outliers, message=FALSE, echo=TRUE, warning=FALSE}
# Function to remove outliers from the data based on the observed lengths.
selected_tickers = c()
for(ticker in sp500_tickers) {
  if (dim(get(ticker))[1] > 1000) {
    selected_tickers <- rbind(selected_tickers, ticker)
  }
}
```

```{r, lengths, message=FALSE, echo=TRUE, warning=FALSE}
# Function to map all the stock data frames lengths into a table.
observation_lengths = c()
for(ticker in sp500_tickers) {
  observation_lengths <- data.frame(lengths = rbind(observation_lengths,
                               dim(get(ticker))[1]))
}
observation_lengths
```

```{r, lengths_histogram, message=FALSE, echo=TRUE, warning=FALSE}
# Function to plot the density of the lengths across the dataset
ggplot(observation_lengths, aes(x= lengths)) + 
  geom_histogram(aes(y=..density..),
                 binwidth= 500,
                 colour="black", fill="white") +
  geom_density(alpha=.2, fill="#FF6666")
```

```{r, dataframe_consolidation, message=FALSE, echo=TRUE, warning=FALSE}
# Function to consolidate the stock data with the calculated technical indicators
for(ticker in selected_tickers) {
    temp <- cbind(get(ticker),
        PERCENT_PRICE = get_percent_values(get(ticker), "price"),
        PERCENT_VOL = get_percent_values(get(ticker), "volume"),
        SMA = get_SMA(get(ticker)),
        EWMA = get_EWMA(get(ticker)),
        MOM = MOM(get(ticker)),
        MACD = MACD(get(ticker)),
        STOCH = STOCH(get(ticker)),
        RSI = RSI(get(ticker)),
        VOR = VOR(get(ticker)),
        PERCENT_CHANGE_20 = get_future_percent_change(get(ticker), 20),
        PERCENT_CHANGE_60 = get_future_percent_change(get(ticker), 60),
        PERCENT_CHANGE_240 = get_future_percent_change(get(ticker), 240),
        FUTURE_CLASS_20 = get_buy_class(get(ticker), 20),
        FUTURE_CLASS_60 = get_buy_class(get(ticker), 60),
        FUTURE_CLASS_240 = get_buy_class(get(ticker), 240)
  )
    assign(ticker, temp)
}
```

```{r}
for(ticker in selected_tickers) {
  curr_val <- cbind(Date = rownames(get(ticker)), get(ticker))
  rownames(curr_val) <- NULL
  assign(ticker, curr_val)
}
```

```{r, table_setup, message=FALSE, echo=TRUE, warning=FALSE}
# Code to setup the stock tables we plan to use in SQLite
for (curr_tick in selected_tickers) {
  ticker_query <- paste(
    "CREATE TABLE IF NOT EXISTS [", curr_tick,
    "] (Date TEXT PRIMARY KEY,
    Open INTEGER,
    High INTEGER,
    Low INTEGER,
    Close INTEGER,
    Volume INTEGER,
    Adjusted INTEGER,
    PERCENT_VOL INTEGER,
    PERCENT_PRICE INTEGER,
    SMA INTEGER,
    EWMA INTEGER,
    MOM INTEGER,
    MACD INTEGER,
    STOCHK INTEGER,
    STOCHD INTEGER,
    RSI INTEGER,
    VOR INTEGER,
    PERCENT_CHANGE_20 INTEGER,
    PERCENT_CHANGE_60 INTEGER,
    PERCENT_CHANGE_240 INTEGER,
    FUTURE_CLASS_20 INTEGER,
    FUTURE_CLASS_60 INTEGER,
    FUTURE_CLASS_240 INTEGER)", sep="")
  dbSendQuery(db, ticker_query)
}
```

```{r, db_mapping, message=FALSE, echo=TRUE, warning=FALSE}
# Function that writes all the data frames to the appropriate SQLite table
for(ticker in selected_tickers) {
  dbWriteTable(conn = db, name = as.character(ticker), value = get(ticker),
                 row.names = FALSE, overwrite = TRUE)
}
```



```{r}
#Stock graph for AAPL
#Indicators shown are Momentum, WMA, SMA, MACD, and EVWMA

#Entire 5 years of data for AAPL
getSymbols("AAPL", from='2014-10-16', to='2019-04-16')
chartSeries(AAPL, TA = "addMomentum();addWMA();addSMA();addMACD();addEVWMA()", theme="white")

#Display 200 day view starting from October 16th
getSymbols("AAPL", from='2018-10-16', to='2019-04-16')
chartSeries(AAPL, TA = "addMomentum();addWMA();addSMA();addMACD();addEVWMA()", theme="white",major.ticks='months',subset='first 28 weeks')

#Displays 50 day view starting from Dec 17th
getSymbols("AAPL", from='2018-12-16', to='2019-04-16')
chartSeries(AAPL, TA = "addMomentum();addWMA();addSMA();addMACD();addEVWMA()", theme="white",major.ticks='months',subset='first 50 days')
```

```{r}
#Stock graph for TSLA
#Indicators shown are Momentum, WMA, SMA, MACD, and EVWMA

#Entire 5 years of data for TSLA
getSymbols("TSLA", from='2014-10-16', to='2019-04-16')
chartSeries(TSLA, TA = "addMomentum();addWMA();addSMA();addMACD();addEVWMA()", theme="white")

#Display 200 day view starting from October 16th
getSymbols("TSLA", from='2018-10-16', to='2019-04-16')
chartSeries(TSLA, TA = "addMomentum();addWMA();addSMA();addMACD();addEVWMA()", theme="white",major.ticks='months',subset='first 28 weeks')

#Displays 50 day view starting from Dec 17th
getSymbols("TSLA", from='2018-12-16', to='2019-04-16')
chartSeries(TSLA, TA = "addMomentum();addWMA();addSMA();addMACD();addEVWMA()", theme="white",major.ticks='months',subset='first 50 days')
```


```{r}
#histogram of all indicators, chosen value is AAPL
aapl_df <- dbGetQuery(db, "SELECT * FROM AAPL")

ggplot(aapl_df, mapping=aes(x=SMA)) + geom_histogram(aes(y=..density..), bins=50) + geom_density(col = "red")
ggplot(aapl_df, mapping=aes(x=EWMA)) + geom_histogram(aes(y=..density..), bins=50) + geom_density(col = "red")
ggplot(aapl_df, mapping=aes(x=MACD)) + geom_histogram(aes(y=..density..), bins=50) + geom_density(col = "red")
ggplot(aapl_df, mapping=aes(x=VOR)) + geom_histogram(aes(y=..density..), bins=50) + geom_density(col = "red")
ggplot(aapl_df, mapping=aes(x=PERCENT_VOL)) + geom_histogram(aes(y=..density..), bins=50) + geom_density(col = "red")
ggplot(aapl_df, mapping=aes(x=PERCENT_PRICE)) + geom_histogram(aes(y=..density..), bins=50) + geom_density(col = "red")
ggplot(aapl_df, mapping=aes(x=RSI)) + geom_histogram(aes(y=..density..), bins=50) + geom_density(col = "red")
ggplot(aapl_df, mapping=aes(x=MOM)) + geom_histogram(aes(y=..density..), bins=50) + geom_density(col = "red")

```
