---
title: "ds-4100-project.Rmd"
author: "Veronica Shei, Edward Wang, Ethan Tang"
date: "3/23/2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(alphavantager)
library(rvest)
library(tidyverse)
library(tryCatchLog)
library(ggplot2)
av_api_key("1MS48Q9F2SIQSHK7")
```

#retrieve S&P 500 company tickers
```{r}
sp500_page <- read_html("https://en.wikipedia.org/wiki/List_of_S%26P_500_companies")
sp500_names <- sp500_page %>% html_nodes("#constituents td:nth-child(2)") %>% html_text()
sp500_names
```

```{r}
# Alpha Vantage API key: KEI93A3FCAX5K5R9
av_get(symbol = "^GSPC", av_fun = "TIME_SERIES_DAILY_ADJUSTED", interval = "1min", outputsize = "full")
```

```{r}
av_get(av_fun = "SECTOR")
```

```{r}
# av_get(symbol = "MSFT", av_fun = "AD", interval = "monthly", time_period = 60)

data_get <- function(ticker) {
  av_get(symbol = ticker, av_fun = "AD", interval = "monthly", time_period = 60)
}
```

```{r}
stocks_test = c("MSFT","TSLA","FB","AAPL")
for (n in stocks_test) {
  try(print(data_get(n)))
}
```

```{r}
# Alpha Vantage API key: KEI93A3FCAX5K5R9
sp500_idx <- av_get(symbol = "^GSPC", av_fun = "TIME_SERIES_DAILY_ADJUSTED", interval = "60min", outputsize = "full")
# Alpha Vantage API key: KEI93A3FCAX5K5R9
fb <- av_get(symbol = "FB", av_fun = "TIME_SERIES_DAILY_ADJUSTED", interval = "60min", outputsize = "full")
```

```{r}
ggplot(sp500_idx,aes(x=timestamp)) + geom_line(aes(y=volume/3000000),color="Red") + scale_y_continuous(sec.axis = sec_axis(~.*3000000, name = "Volume")) + geom_line(aes(y=adjusted_close)) + geom_smooth(aes(y=adjusted_close),method='lm')
```
```{r}
response <- logical(nrow(sp500_idx))
# whether it is up or down after a year
for (n in 1:nrow(sp500_idx)) {
  if (n < nrow(sp500_idx) - 365) {
    response[n] <- sp500_idx[n+ 365,6] > sp500_idx[n,6]
  }
}
sp500_idx = cbind(sp500_idx,response)
rel_idx=nrow(sp500_idx) - 365
sp500_anal = sp500_idx[1:rel_idx,]
sp500_anal
```

```{r}
# determining a training size based on 70% of the dataset
training_perc = .70
training_size = round(dim(sp500_anal)[[1]] * training_perc,0)

# creating a random index with the determined training size for selecting the training/testing set
training_idx = sample(nrow(sp500_anal),size=training_size,replace=FALSE)
train_df = sp500_anal[training_idx,]
test_df = sp500_anal[-training_idx,]

# 
pred <- step(glm(response ~ timestamp + adjusted_close + volume, train_df, family=binomial), direction="both")
# Stepping removed Embarked, Parch, Fare as the AIC was higher than leaving them in the model
# Note the stepping removed the variables from the full model above that were above a .05 p-value
summary(pred)
```

```{r}
# testing model against test dataset
# rounding applies a threshold of 50% probability for survival
predicted <- round(predict(pred, test_df, type="response"),0)

# place predictions and actual class into a dataframe
results <- data.frame(predicted, test_df$response)
head(results)

# Output the accuracy of the model
test_size = dim(sp500_anal)[1] - training_size
accuracy = (count(results %>% filter(predicted==test_df.response))) / test_size
print(accuracy)
```

```{r}
count(results %>% filter(predicted==test_df.response))
```
